### ISSUE TITLE
Material GUID references on fbx files are not replaced

### ISSUE THREAD

**Issue by danilodelponte** [jeffjadulco/unity-guid-regenerator#7]
Scenario:

1. Given that you have a FBX file with a material mapped to it (*)
2. When you regenerate the material GUID file
3. Then the FBX loses the reference to it

(*) Tested with FBX using legacy standard material creation mode and embedded materials

This appears to happen because the reference to the material is in the FBX meta file and not the asset file. FBX meta file ex::
```
fileFormatVersion: 2
guid: 3ea85db3da6e4524cb0ff3011bcbaff7
ModelImporter:
  serializedVersion: 21
  internalIDToNameTable: []
  externalObjects:
  - first:
      type: UnityEngine:Material
      assembly: UnityEngine.CoreModule
      name: Howl_M
    second: {fileID: 2100000, guid: 253e123fd6b1fe74a8dfddc60c2a7073, type: 2} // <- here is the material GUID inside FBX meta
  materials:
    materialImportMode: 1
(...)
```
